export const emailStyles = {
  main: {
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    WebkitFontSmoothing: 'antialiased',
    fontSize: '14px',
    lineHeight: '1.4',
    margin: '0',
    padding: '0',
    msTextSizeAdjust: '100%',
    WebkitTextSizeAdjust: '100%',
    backgroundColor: '#f8f9fa',
  },
  container: {
    maxWidth: '600px',
    margin: '0 auto',
    padding: '20px',
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  },
  header: {
    textAlign: 'center' as const,
    padding: '20px 0',
    backgroundColor: '#0a4d7c',
    color: 'white',
    borderRadius: '6px 6px 0 0',
    marginBottom: '20px',
    fontSize: '24px',
    fontWeight: '600',
  },
  greeting: { fontSize: '22px', fontWeight: '600', color: '#333', marginBottom: '10px' },
  paragraph: { color: '#555', marginBottom: '20px', fontSize: '16px' },
  tableContainer: {
    margin: '20px 0',
    borderRadius: '6px',
    overflow: 'hidden',
    boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
  },
  table: { width: '100%', borderCollapse: 'collapse' as const },
  tableHeader: {
    backgroundColor: '#0a4d7c',
    color: 'white',
    textAlign: 'left' as const,
    padding: '12px 15px',
    fontWeight: '600',
    fontSize: '14px',
  },
  tableData: { padding: '10px 15px', borderBottom: '1px solid #e0e0e0', fontSize: '14px' },
  tableRowEven: { backgroundColor: '#f5f7fa' },
  noTransaction: { textAlign: 'center' as const, padding: '20px', color: '#777', fontStyle: 'italic' },
  statusSuccessful: {
    color: '#10b981',
    fontWeight: '600',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    padding: '4px 8px',
    borderRadius: '4px',
  },
  statusFailed: {
    color: '#ef4444',
    fontWeight: '600',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    padding: '4px 8px',
    borderRadius: '4px',
  },
  footer: {
    textAlign: 'center' as const,
    marginTop: '30px',
    padding: '20px',
    color: '#666',
    fontSize: '14px',
    borderTop: '1px solid #eaeaea',
  },
  companyInfo: { marginTop: '15px', fontSize: '12px', color: '#888' },
};
